name: Build
on: [push, pull_request]

env:
  EM_VERSION: 3.1.57
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Setup cache
      id: cache-system-libraries
      uses: actions/cache@v4
      with:
        path: ${{env.EM_CACHE_FOLDER}}
        key: ${{env.EM_VERSION}}-${{ runner.os }}

    - name: Install Deps
      run: |
        sudo apt update
        sudo apt install ninja-build

    - name: Setup Emscripten toolchain
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{ env.EM_VERSION }}
        actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

    - name: Build
      run: |
        npm install
        npm run build
        npm pack
        cp example/index.html dist/
        sed 's/\.\.\/dist\//.\//' example/example.js > dist/example.js

    - name: Upload package tarball
      uses: actions/upload-artifact@v4
      with:
        name: package-tarball
        path: np2-wasm-*.tgz

    - name: Upload artifacts for GitHub Pages
      uses: actions/upload-pages-artifact@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        path: dist

  deploy:
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
