name: Build
on: [push, pull_request]

env:
  EM_VERSION: 3.1.46
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Setup cache
      id: cache-system-libraries
      uses: actions/cache@v3
      with:
        path: ${{env.EM_CACHE_FOLDER}}
        key: ${{env.EM_VERSION}}-${{ runner.os }}

    - name: Install Deps
      run: |
        sudo apt update
        sudo apt install ninja-build

    - name: Setup Emscripten toolchain
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: ${{ env.EM_VERSION }}
        actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

    - name: Build
      run: |
        npm install
        npm run build
        npm pack

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tarball
        path: np2-wasm-*.tgz
